permalink: /:year/:month/:day/:title
paginate: 10
markdown: redcarpet
redcarpet:
   extensions: ["hard_wrap","autolink","tables","fenced_code_blocks","disable_indented_code_blocks","no_intra_emphasis","space_after_headers","underline"]

# 作者信息
author: 
  name: blackli
  email: lihaho@gmail.com
  link: http://me.wuseci.com
  weibo: http://weibo.com/blackli
  github: http://github.com/blackli

# 站点信息
title: blackli
description: 
url: http://me.wuseci.com
rss_url: /pages/atom.xml

# gavatar头像及Favicon
gavatar: /public/upload/avatar/avatar.png
favicon: /public/upload/avatar/favicon.ico

# google analytics 设置
#ga:
#  id: UA-44312631-1
#  url: opjasee.com

# disqus 设置
disqus:
  shortname: blackli

# 主题设置，自动激活某个标签
active: 运维

# 首页除了最新文章外按标签分类显示
cates:
  - OpenLDAP

# 中文本地化
locals:
  tags: 标签
  about: 关于
  newest: 最新文章
